# Generated by Django 5.1.4 on 2025-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id_hash', models.CharField(max_length=64, unique=True)),
                ('encrypted_client_id', models.BinaryField()),
                ('encrypted_access_token', models.BinaryField()),
                ('encrypted_refresh_token', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
