# Generated by Django 5.2.8 on 2025-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsoftuser',
            options={'ordering': ['-last_login'], 'verbose_name': 'Usuario de Microsoft', 'verbose_name_plural': 'Usuarios de Microsoft'},
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='client_id_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash del Client ID de Azure AD', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del usuario'),
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='encrypted_access_token',
            field=models.BinaryField(help_text='Access token encriptado, expira en ~1 hora'),
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='encrypted_client_id',
            field=models.BinaryField(help_text='Client ID encriptado con Fernet + PBKDF2'),
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='encrypted_refresh_token',
            field=models.BinaryField(blank=True, help_text='Refresh token encriptado para renovación automática', null=True),
        ),
        migrations.AlterField(
            model_name='microsoftuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (login o refresh)'),
        ),
        migrations.AddIndex(
            model_name='microsoftuser',
            index=models.Index(fields=['-created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='microsoftuser',
            index=models.Index(fields=['-last_login'], name='idx_last_login'),
        ),
    ]
